//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public long Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public long Year { get; set; }
        public string Vin { get; set; }
        public string State { get; set; }
        public string Plate { get; set; }
        public long Owner { get; set; }
        public string ProdDate { get; set; }
    }
}
