//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public long Id { get; set; }
        public Nullable<long> AppointmentID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> CarID { get; set; }
        public string Description { get; set; }
        public long Active { get; set; }
        public long Visible { get; set; }
    }
}
